### ISSUE TITLE
List of supported commands

### ISSUE THREAD

**Issue by simongranger** [jonstoneman/appium-windows-driver#6]
Is there a published list of supported commands?

**Comment by stoneman** [comment]
This project has been adopted by the Appium team so take a look at https://github.com/appium/appium-windows-driver for the latest code and documentation.  I don't believe there is a list of supported commands yet and, since this driver is mainly a proxy of https://github.com/Microsoft/WinAppDriver/, the supported commands are mainly dependent on the development of that service.
